CREATE DATABASE IF NOT EXISTS grafana
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'grafana'@'%' IDENTIFIED BY 'Grafana_DB_2026_Secure!';
GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'%';
FLUSH PRIVILEGES;
